/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ShellRouteImport } from './routes/_shell'
import { Route as ShellIndexRouteImport } from './routes/_shell/index'
import { Route as ShellTasksRouteImport } from './routes/_shell/tasks'
import { Route as AuthSsoLandingRouteImport } from './routes/auth.sso.landing'

const ShellRoute = ShellRouteImport.update({
  id: '/_shell',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellIndexRoute = ShellIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ShellRoute,
} as any)
const ShellTasksRoute = ShellTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => ShellRoute,
} as any)
const AuthSsoLandingRoute = AuthSsoLandingRouteImport.update({
  id: '/auth/sso/landing',
  path: '/auth/sso/landing',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof ShellIndexRoute
  '/tasks': typeof ShellTasksRoute
  '/auth/sso/landing': typeof AuthSsoLandingRoute
}
export interface FileRoutesByTo {
  '/tasks': typeof ShellTasksRoute
  '/': typeof ShellIndexRoute
  '/auth/sso/landing': typeof AuthSsoLandingRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_shell': typeof ShellRouteWithChildren
  '/_shell/tasks': typeof ShellTasksRoute
  '/_shell/': typeof ShellIndexRoute
  '/auth/sso/landing': typeof AuthSsoLandingRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/tasks' | '/auth/sso/landing'
  fileRoutesByTo: FileRoutesByTo
  to: '/tasks' | '/' | '/auth/sso/landing'
  id:
    '__root__' | '/_shell' | '/_shell/tasks' | '/_shell/' | '/auth/sso/landing'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ShellRoute: typeof ShellRouteWithChildren
  AuthSsoLandingRoute: typeof AuthSsoLandingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_shell': {
      id: '/_shell'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ShellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell/': {
      id: '/_shell/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ShellIndexRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/tasks': {
      id: '/_shell/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof ShellTasksRouteImport
      parentRoute: typeof ShellRoute
    }
    '/auth/sso/landing': {
      id: '/auth/sso/landing'
      path: '/auth/sso/landing'
      fullPath: '/auth/sso/landing'
      preLoaderRoute: typeof AuthSsoLandingRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ShellRouteChildren {
  ShellTasksRoute: typeof ShellTasksRoute
  ShellIndexRoute: typeof ShellIndexRoute
}

const ShellRouteChildren: ShellRouteChildren = {
  ShellTasksRoute: ShellTasksRoute,
  ShellIndexRoute: ShellIndexRoute,
}

const ShellRouteWithChildren = ShellRoute._addFileChildren(ShellRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  ShellRoute: ShellRouteWithChildren,
  AuthSsoLandingRoute: AuthSsoLandingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
