/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ShellRouteImport } from './routes/_shell'
import { Route as ShellIndexRouteImport } from './routes/_shell/index'
import { Route as ShellAuditRouteImport } from './routes/_shell/audit'
import { Route as ShellConversationsRouteImport } from './routes/_shell/conversations'
import { Route as ShellLibraryRouteImport } from './routes/_shell/library'
import { Route as ShellTasksRouteImport } from './routes/_shell/tasks'
import { Route as ShellCConversationIdRouteImport } from './routes/_shell/c.$conversationId'
import { Route as AuthSsoLandingRouteImport } from './routes/auth.sso.landing'

const ShellRoute = ShellRouteImport.update({
  id: '/_shell',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellIndexRoute = ShellIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ShellRoute,
} as any)
const ShellAuditRoute = ShellAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => ShellRoute,
} as any)
const ShellConversationsRoute = ShellConversationsRouteImport.update({
  id: '/conversations',
  path: '/conversations',
  getParentRoute: () => ShellRoute,
} as any)
const ShellLibraryRoute = ShellLibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => ShellRoute,
} as any)
const ShellTasksRoute = ShellTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => ShellRoute,
} as any)
const ShellCConversationIdRoute = ShellCConversationIdRouteImport.update({
  id: '/c/$conversationId',
  path: '/c/$conversationId',
  getParentRoute: () => ShellRoute,
} as any)
const AuthSsoLandingRoute = AuthSsoLandingRouteImport.update({
  id: '/auth/sso/landing',
  path: '/auth/sso/landing',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof ShellIndexRoute
  '/audit': typeof ShellAuditRoute
  '/conversations': typeof ShellConversationsRoute
  '/library': typeof ShellLibraryRoute
  '/tasks': typeof ShellTasksRoute
  '/c/$conversationId': typeof ShellCConversationIdRoute
  '/auth/sso/landing': typeof AuthSsoLandingRoute
}
export interface FileRoutesByTo {
  '/audit': typeof ShellAuditRoute
  '/conversations': typeof ShellConversationsRoute
  '/library': typeof ShellLibraryRoute
  '/tasks': typeof ShellTasksRoute
  '/': typeof ShellIndexRoute
  '/c/$conversationId': typeof ShellCConversationIdRoute
  '/auth/sso/landing': typeof AuthSsoLandingRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_shell': typeof ShellRouteWithChildren
  '/_shell/audit': typeof ShellAuditRoute
  '/_shell/conversations': typeof ShellConversationsRoute
  '/_shell/library': typeof ShellLibraryRoute
  '/_shell/tasks': typeof ShellTasksRoute
  '/_shell/': typeof ShellIndexRoute
  '/_shell/c/$conversationId': typeof ShellCConversationIdRoute
  '/auth/sso/landing': typeof AuthSsoLandingRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/audit'
    | '/conversations'
    | '/library'
    | '/tasks'
    | '/c/$conversationId'
    | '/auth/sso/landing'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/audit'
    | '/conversations'
    | '/library'
    | '/tasks'
    | '/'
    | '/c/$conversationId'
    | '/auth/sso/landing'
  id:
    | '__root__'
    | '/_shell'
    | '/_shell/audit'
    | '/_shell/conversations'
    | '/_shell/library'
    | '/_shell/tasks'
    | '/_shell/'
    | '/_shell/c/$conversationId'
    | '/auth/sso/landing'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ShellRoute: typeof ShellRouteWithChildren
  AuthSsoLandingRoute: typeof AuthSsoLandingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_shell': {
      id: '/_shell'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ShellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell/': {
      id: '/_shell/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ShellIndexRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/audit': {
      id: '/_shell/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof ShellAuditRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/conversations': {
      id: '/_shell/conversations'
      path: '/conversations'
      fullPath: '/conversations'
      preLoaderRoute: typeof ShellConversationsRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/library': {
      id: '/_shell/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof ShellLibraryRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/tasks': {
      id: '/_shell/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof ShellTasksRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/c/$conversationId': {
      id: '/_shell/c/$conversationId'
      path: '/c/$conversationId'
      fullPath: '/c/$conversationId'
      preLoaderRoute: typeof ShellCConversationIdRouteImport
      parentRoute: typeof ShellRoute
    }
    '/auth/sso/landing': {
      id: '/auth/sso/landing'
      path: '/auth/sso/landing'
      fullPath: '/auth/sso/landing'
      preLoaderRoute: typeof AuthSsoLandingRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ShellRouteChildren {
  ShellAuditRoute: typeof ShellAuditRoute
  ShellConversationsRoute: typeof ShellConversationsRoute
  ShellLibraryRoute: typeof ShellLibraryRoute
  ShellTasksRoute: typeof ShellTasksRoute
  ShellIndexRoute: typeof ShellIndexRoute
  ShellCConversationIdRoute: typeof ShellCConversationIdRoute
}

const ShellRouteChildren: ShellRouteChildren = {
  ShellAuditRoute: ShellAuditRoute,
  ShellConversationsRoute: ShellConversationsRoute,
  ShellLibraryRoute: ShellLibraryRoute,
  ShellTasksRoute: ShellTasksRoute,
  ShellIndexRoute: ShellIndexRoute,
  ShellCConversationIdRoute: ShellCConversationIdRoute,
}

const ShellRouteWithChildren = ShellRoute._addFileChildren(ShellRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  ShellRoute: ShellRouteWithChildren,
  AuthSsoLandingRoute: AuthSsoLandingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
